config/routes.rb
Rails.application.routes.draw do


  get 'errors/not_found'

  get 'errors/internal_server_error'

  get 'pages/welcome'
  get 'pages/terms'
  get 'pages/privacy'
  # get 'pages/swish_privacy'

  get "dashboard/index"  

  get 'react_examples/component', to: 'react_examples#component', as: :component
  
  devise_for :clients, :controllers => {
    :omniauth_callbacks   =>   'clients/omniauth_callbacks',
    :confirmations        =>   'clients/confirmations',
    :registrations        =>   'clients/registrations',
    :invitations          =>   'clients/invitations'
  }

  resources :websites

  resources :messages, only: [:new, :create]
  resources :support_conversations, only: [:index, :show, :new, :create]

  resources :clients do
    member do 
      get :index_invoices
    end    
    # member { put :toggle_menu_preference }
    resources :websites do 
      resources :subscriptions
      resources :features
    end
  end

  # https://mattbrictson.com/dynamic-rails-error-pages
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  

  # Consume Stripe Webhooks: https://github.com/integrallis/stripe_event
  mount StripeEvent::Engine, at: '/stripe_webhooks' # provide a custom path

  root to: "pages#welcome"

end

app/models/website.rb
# == Schema Information
#
# Table name: websites
#
#  id                     :integer          not null, primary key
#  client_id              :integer
#  features_id            :integer
#  billing_units          :integer          default(30)
#  name                   :string(255)
#  app_type               :string(255)
#  ssl                    :boolean          default(FALSE)
#  cdn                    :boolean          default(FALSE)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  billing_currency       :string(255)      default("AUD")
#  paid                   :boolean
#  stripe_subscription_id :string(255)
#  hosting_units          :string(255)
#  monthly_cost_cents     :integer          default(2500)
#  production_url         :string(255)
#  staging_url            :string(255)
#  live_status            :string(255)      default("live")
#  slug                   :string(255)
#
# Indexes
#
#  index_websites_on_client_id    (client_id)
#  index_websites_on_features_id  (features_id)
#  index_websites_on_slug         (slug) UNIQUE
#

class Website < ApplicationRecord
  belongs_to :client, inverse_of: :websites
  has_many :features, dependent: :destroy, inverse_of: :website
  accepts_nested_attributes_for :features
  has_many :support_conversations
  before_save :calculate_monthly_cost

  # Better URL Slugs
  extend FriendlyId
  friendly_id :name, use: :slugged
  validates :name, uniqueness: true, presence: true


  def calculate_monthly_cost
    monthly = 0
    monthly += self.billing_units
    
    # Add value of each feature into monthly cost
    self.features.each do |feature|
      monthly += (feature.billing_units * feature.quantity)
    end

    # raise
    self.monthly_cost_cents = monthly * 100
    self.hosting_units = monthly
  end


end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  
  before_filter :load_client
  before_action :authenticate_client!
  before_action :set_website, only: [:show, :edit, :update, :destroy]
  # before_action :set_client

  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.where(client_id: current_client.uuid) 
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
  end

  # GET /websites/new
  def new
    @website = websites.new
    @website.features.build
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites
  # POST /websites.jsonclient_website_path
  def create
    @website = websites.new(website_params)

    respond_to do |format|
      if @website.save
        flash[:notice] = :success
        format.html { redirect_to @website, notice: 'Website was successfully created.' }
        format.json { render :show, status: :created, location: @website }
      else
        format.html { render :new }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1
  # PATCH/PUT /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { render :show, status: :ok, location: @website }
      else
        format.html { render :edit }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website.destroy
    respond_to do |format|
      format.html { redirect_to websites_url, notice: 'Website was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.friendly.find(params[:id])
    end

    def load_client
      params[:client_id] ? @client = Client.friendly.find(params[:client_id]) : @client = current_client
    end

    def websites
      params[:client_id] ? @client.websites : Website
    end    

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_params
      params.require(:website).permit(:client_id, :features_id, :billing_units, :name, :app_type, :ssl, :cdn, :monthly_cost_cents)
    end
    
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/websites/_form.html.haml
= simple_form_for [@client, @website] do |w|
  = simple_fields_for :features do |f|
    = f.error_notification

    .form-inputs
      / # = f.association :website
      = f.input :billing_units
      = f.input :quantity
      = f.input :name

    .form-inputs
      = w.association :client
      / # = w.association :features
      = w.input :billing_units
      = w.input :name
      = w.input :app_type
      = w.input :ssl
      = w.input :cdn

  .form-actions
    = w.button :submit

app/views/websites/edit.html.haml
%h1 Editing website

= render 'form'

= link_to 'Show', @website
\|
= link_to 'Back', websites_path

app/views/websites/index.html.haml
- content_for :title, 'Your websites'
- content_for :sub_title do 
  = "Lists all websites we have on file for you as a client"
- @websites.each do |website|
  = render :partial => 'layouts/website_full', locals: {subscription: website.stripe_subscription_id ? Stripe::Subscription.retrieve(website.stripe_subscription_id) : nil, website: website}

- if current_client.try(:admin?)
  = link_to 'New Website', new_client_website_path(current_client)

app/views/websites/new.html.haml
%h1 New website

= render 'form'

= link_to 'Back', client_websites_path(params[:client_id])

app/views/websites/show.html.haml
- content_for :title, @website.name
- content_for :sub_title do 
  = "Information regarding your website"
-if @website.stripe_subscription_id
  - subscription = Stripe::Subscription.retrieve(@website.stripe_subscription_id)
  .ui.segment
    %a.ui.ribbon.label{class: "subscription-#{subscription.status}"} #{subscription.status.capitalize}
    .ui.divided.items
      .item
        .image
        .content
          %a.header #{@website.name ? @website.name : @client.business_name}
          .meta
            %span #{subscription.plan.name}
          .description
            %p
          .extra
            = form_tag websites_path do
              - if flash[:error].present?
                #error_explanation
                  %p= flash[:error]   
              .ui.right.floated     

            = link_to 'Show', client_website_path(current_client, @website), class: "ui basic button"
            = link_to 'Edit', edit_client_website_path(current_client, @website), class: "ui basic button"
            = link_to 'Destroy', client_website_path(current_client, @website), :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "ui basic button"
          .extra 
            - @website.features.each do |feature|
              .ui.label
                = feature
            %p
              %b Billing units:
              = @website.monthly_cost_cents
            %p
              %b Name:
              = @website.name
            %p
              %b App type:
              = @website.app_type
            %p
              %b Ssl:
              = @website.ssl
            %p
              %b Cdn:
              = @website.cdn                    

%p#notice= notice