config/routes.rb
Rails.application.routes.draw do


  get 'errors/not_found'

  get 'errors/internal_server_error'

  get 'pages/welcome'
  get 'pages/terms'
  get 'pages/privacy'
  # get 'pages/swish_privacy'

  get "dashboard/index"  

  get 'react_examples/component', to: 'react_examples#component', as: :component
  
  devise_for :clients, :controllers => {
    :omniauth_callbacks   =>   'clients/omniauth_callbacks',
    :confirmations        =>   'clients/confirmations',
    :registrations        =>   'clients/registrations',
    :invitations          =>   'clients/invitations'
  }

  resources :websites

  resources :messages, only: [:new, :create]
  resources :support_conversations, only: [:index, :show, :new, :create]

  resources :clients do
    member do 
      get :index_invoices
    end    
    # member { put :toggle_menu_preference }
    resources :websites do 
      resources :subscriptions
      resources :features
    end
  end

  # https://mattbrictson.com/dynamic-rails-error-pages
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  

  # Consume Stripe Webhooks: https://github.com/integrallis/stripe_event
  mount StripeEvent::Engine, at: '/stripe_webhooks' # provide a custom path

  root to: "pages#welcome"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_client!
  before_action :set_client, only: [:show, :edit, :update, :destroy, :index]
 

  def index

    # Facebook Oauth doesn't always return email - demand to enter
    if @no_email
      flash[:success] = "Successfully authorised from Facebook account"
      flash[:error] = "Facebook could not provide your email; please enter here"
      redirect_to edit_client_registration_path(@client)
    end
    
    @websites = Website.where(client_id: @client.uuid)  

    # @websites.each do |website|
    #   subscription = Stripe::Subscription.retrieve(website.stripe_subscription_id)  
    # end

    # Talk to Stripe API to retreive their current subscription      

    
    # @status = @subscription.status

    # Talk to Stripe API to retrieve their invoices

    @invoices = Stripe::Invoice.list(:customer => @client.stripe_account_id, limit: 6)

    @upcoming = (@client.stripe_account_id? and @client.subscribed?) ? 
      Stripe::Invoice.upcoming(:customer => @client.stripe_account_id) : 
      nil

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = current_client
      # @subscribed = @client.stripe_subscription_id?
      @no_email = @client.email.exclude?('@')
      @client_currency = @client.billing_currency
    end  

end

app/views/dashboard/index.haml
- content_for :title do
  / # = react_component('PageTitle', {clientName: @client.business_name ? @client.business_name : @client.contact_name, client: @client}, {server_side: false})
  = "Your client dashboard"
- content_for :sub_title do 
  = "Your homepage shows a general overview of your account"

/ If customer has existing invoices, show up here
.site-or-invoice-group
  .ui.grid
    .two.column.row
      .left.floated.column
        %h2 Websites Summary
        %div{:class => 'counter-wrapper'}
          %h1 Counter
          %form{:class => 'counter'}
            %input{:id => 'counter', :name => 'counter', :type => 'number', :value => '16'}/
            %button{:id => 'increment'} Increment            
            %button{:id => 'decrement'} Decrement
        = javascript_pack_tag 'counter'
        = stylesheet_pack_tag 'counter'

      .right.floated.right.aligned.column
        = link_to "My Sites", client_websites_path(current_client), class: "ui basic button #{"disabled" if current_client.websites.empty?}"
  - if @websites.nil? || @websites.empty?
    = render :partial => 'layouts/none_yet', locals: {type: "websites"}       
  - @websites.each do |website|
    = render :partial => 'layouts/website_simple', locals: {subscription: website.stripe_subscription_id ? Stripe::Subscription.retrieve(website.stripe_subscription_id) : nil, website: website}

.site-or-invoice-group
  .ui.grid
    .two.column.row
      .left.floated.column
        %h2 Invoice Summary
      .right.floated.right.aligned.column
        = link_to "My Invoices", index_invoices_client_path(current_client), class: "ui basic button #{"disabled" if (current_client.stripe_account_id.nil? and !current_client.subscribed?)}"


  - if @upcoming


    %ul.latest-charges

    
      %h5.pad-left Upcoming Invoices
      - invoice = @upcoming
      = render :partial => "layouts/invoice_simple", locals: { invoice: @upcoming, icon: "calendar outline", inactive: false }

      %h5.pad-left Latest
      - invoice = @invoices.data.shift
      = render :partial => "layouts/invoice_simple", locals: { invoice: invoice, icon: "checkmark green", inactive: false }      

      %h5.pad-left{class: @invoices.data.empty? ? "faded" : "" } Completed
      - @invoices.data.each do |invoice|  
        = render :partial => "layouts/invoice_simple", locals: { invoice: invoice, icon: "checkmark", inactive: true }     

  - if @upcoming
    .site-or-invoice-group
      .ui.grid
        .two.column.row
          .left.floated.column
            / %h2 Invoice Summary
          .right.floated.right.aligned.column
            = link_to "View More Invoices", index_invoices_client_path(current_client), class: "ui basic button #{"disabled" if (current_client.stripe_account_id.nil? and !current_client.subscribed?)}"                         


  - else
    = render :partial => 'layouts/none_yet', locals: {type: "invoices"}       