config/routes.rb
Rails.application.routes.draw do


  get 'errors/not_found'

  get 'errors/internal_server_error'

  get 'pages/welcome'
  get 'pages/terms'
  get 'pages/privacy'
  # get 'pages/swish_privacy'

  get "dashboard/index"  

  get 'react_examples/component', to: 'react_examples#component', as: :component
  
  devise_for :clients, :controllers => {
    :omniauth_callbacks   =>   'clients/omniauth_callbacks',
    :confirmations        =>   'clients/confirmations',
    :registrations        =>   'clients/registrations',
    :invitations          =>   'clients/invitations'
  }

  resources :websites

  resources :messages, only: [:new, :create]
  resources :support_conversations, only: [:index, :show, :new, :create]

  resources :clients do
    member do 
      get :index_invoices
    end    
    # member { put :toggle_menu_preference }
    resources :websites do 
      resources :subscriptions
      resources :features
    end
  end

  # https://mattbrictson.com/dynamic-rails-error-pages
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  

  # Consume Stripe Webhooks: https://github.com/integrallis/stripe_event
  mount StripeEvent::Engine, at: '/stripe_webhooks' # provide a custom path

  root to: "pages#welcome"

end

app/models/support_conversation.rb
# == Schema Information
#
# Table name: support_conversations
#
#  id          :integer          not null, primary key
#  author_id   :integer
#  receiver_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  website_id  :integer
#
# Indexes
#
#  index_support_conversations_on_author_id    (author_id)
#  index_support_conversations_on_receiver_id  (receiver_id)
#  index_support_conversations_on_website_id   (website_id)
#

class SupportConversation < ApplicationRecord
  
  # https://www.sitepoint.com/build-a-messaging-system-with-rails-and-actioncable/  
  belongs_to :author, class_name: 'Client'
  belongs_to :receiver, class_name: 'Client'
  belongs_to :website, optional: true  
  has_many :messages, -> { order(created_at: :asc) }, dependent: :destroy, inverse_of: :support_conversation
  # validates :author, uniqueness: {scope: :receiver}
  accepts_nested_attributes_for :messages

  scope :participating, -> (client) do
    where("(support_conversations.author_id = ? OR support_conversations.receiver_id = ?)", client.uuid, client.uuid)
  end  

  scope :between, -> (sender_id, receiver_id) do
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id)).limit(1)
  end

  def with(current_client)
    author == current_client ? receiver : author
  end 

   def participates?(client)
    author == client || receiver == client
  end

end

app/controllers/support_conversations_controller.rb
class SupportConversationsController < ApplicationController
  before_action :set_support_conversation, except: [:index, :new, :create]
  before_action :check_participating!, except: [:index, :new, :create]
  before_action :set_admin_receiver

  # GET /support_conversations
  # GET /support_conversations.json
  def index
    @support_conversations = SupportConversation.participating(current_client).order('updated_at DESC')
  end

  # GET /support_conversations/1
  # GET /support_conversations/1.json
  def show
    @message = Message.new
  end

  # GET /support_conversations/new
  def new
    @receiver = Client.friendly.find(params[:receiver_id])
    @websites = current_client.websites
    @support_conversation = SupportConversation.new
    @message = @support_conversation.messages.build
  end

  # POST /support_conversations
  # POST /support_conversations.json
  def create
    @support_conversation = SupportConversation.new(support_conversation_params)

    respond_to do |format|
      if @support_conversation.save
        format.html { 
          redirect_to @support_conversation, notice: 'Support conversation was successfully created.'
          ClientMailer.new_message_received(@support_conversation.messages.last, @support_conversation).deliver_later
        }
        format.json { render :show, status: :created, location: @support_conversation }
      else
        format.html { render :new }
        format.json { render json: @support_conversation.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_support_conversation
      @support_conversation = SupportConversation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def support_conversation_params
      params.require(:support_conversation).permit(:author_id, :receiver_id, :website_id, :messages_attributes => [:body, :attached_image, :client_id])
    end

    def check_participating!
      redirect_to dashboard_index_path unless @support_conversation && @support_conversation.participates?(current_client)
    end 

    def set_admin_receiver
      @support_receiver = Client.find_by(admin: true)
      # @support_conversation = current_client.authored_support_conversations.build
    end    

end

app/helpers/support_conversations_helper.rb
module SupportConversationsHelper
end

app/views/support_conversations/_form.html.haml
- @selected = params[:website_id] ? @websites.where(id: params[:website_id])[0] : @websites.last
= simple_form_for(@support_conversation) do |f|
  = f.error_notification

  .form-inputs
    = f.hidden_field :receiver_id, value: @receiver.uuid
    = f.hidden_field :author_id, value: current_client.uuid  
    = f.association :website, collection: @websites, selected: @selected, required: true
    / https://github.com/plataformatec/simple_form/wiki/Nested-Models
    = f.simple_fields_for :messages do |m|
      .ui.field
        = m.label "Message"
        = m.text_area :body, required: true
        = m.hidden_field :client_id, value: current_client.uuid

  
    .ui.field
      = f.button :submit

app/views/support_conversations/_support_conversation.haml
- icon = "email"
- last = support_conversation.messages.last
- message_time = last.created_at.in_time_zone(ENV["time_zone"])
%li.charge
  .ui.right.aligned.grid
    .right.aligned.sixteen.wide.column
      .ui.right.aligned.stackable.grid
        .left.floated.left.aligned.twelve.wide.column
          .ui.items
            .ui.item
              .content
                .header
                  - if support_conversation.website_id?
                    = "Support request for #{support_conversation.website.name}"
                  - else
                    = "Chatting with #{support_conversation.with(current_client).contact_name}"
                %hr/
                .description
                  %em= last.body.truncate(50)
                .meta
                  %span
                    = link_to 'View conversation', support_conversation_path(support_conversation)
        .right.floated.right.aligned.four.wide.column
          .ui.items
            .ui.item
              .content
                .meta
                  - if last.client.oauth_avatar?
                    = image_tag last.client.oauth_avatar, class: "ui avatar image"
                  - else
                    = image_tag last.client.avatar.url(:thumb), class: "ui avatar image"
                .meta
                  %span
                    %strong= time_ago_in_words(message_time)
                    ago
                    %br/
                    by
                    %strong= last.client.contact_name  
                  

app/views/support_conversations/edit.html.haml
%h1 Editing support_conversation

= render 'form'

= link_to 'Show', @support_conversation
\|
= link_to 'Back', support_conversations_path

app/views/support_conversations/index.html.haml
- content_for :title do 
  = "Your support conversations"
- content_for :sub_title do 
  = "View and respond to the conversation below"
%ul.latest-charges
  .ui.comments
    -if @support_conversations.empty?
      %li.charge
        .ui.center.aligned.grid
          .center.aligned.sixteen.wide.column
            .ui.items
              .ui.item
                .content
                  .header
                    No Support Conversations to show at this point  
    %li.charge
      .ui.center.aligned.grid
        .center.aligned.sixteen.wide.column
          .ui.items
            .ui.item
              .content
                -unless current_client.websites.empty?
                  = link_to 'Create a New Support Request', new_support_conversation_path(receiver_id: @support_receiver), class: "ui button basic"
                = link_to 'New General Enquiry', new_message_path(receiver_id: @support_receiver, generic_contact: true), class: "ui button basic"
                      
    = render @support_conversations

%br

/ # = link_to 'New Support conversation', new_support_conversation_path

app/views/support_conversations/new.html.haml
- content_for :title do
  New Support Conversation with #{@receiver.contact_name}
- content_for :sub_title do
  Please detail the issues you are having and upload any helpful screenshots in the form below
%ul.latest-charges
  .ui.comments  
    %li.charge
      .ui.center.aligned.grid
        .center.aligned.sixteen.wide.column
          .ui.items
            .ui.item
              .content  
                = render 'form'

app/views/support_conversations/show.html.haml
- content_for :title do 
  = "Your conversation with #{@support_conversation.with(current_client).contact_name}"
- content_for :sub_title do 
  = "Lodge support requests and view your support history here"
.ui.comments.segment
  -if @support_conversation
    - if @support_conversation.website_id?
      %h3.ui.dividing.header= "Support request for #{@support_conversation.website.name}"
    - else
      %h3.ui.dividing.header= "Chatting with #{@support_conversation.with(current_client).contact_name}"  
    / Chatting with #{@support_conversation.with(current_client).contact_name}
    = render @support_conversation.messages
    = simple_form_for @message do |f|
      = hidden_field_tag 'support_conversation_id', @support_conversation.id
      .ui.field
        = f.text_area :body
      .ui.field
        = f.button :submit, "Send"