config/routes.rb
Rails.application.routes.draw do


  get 'errors/not_found'

  get 'errors/internal_server_error'

  get 'pages/welcome'
  get 'pages/terms'
  get 'pages/privacy'
  # get 'pages/swish_privacy'

  get "dashboard/index"  

  get 'react_examples/component', to: 'react_examples#component', as: :component
  
  devise_for :clients, :controllers => {
    :omniauth_callbacks   =>   'clients/omniauth_callbacks',
    :confirmations        =>   'clients/confirmations',
    :registrations        =>   'clients/registrations',
    :invitations          =>   'clients/invitations'
  }

  resources :websites

  resources :messages, only: [:new, :create]
  resources :support_conversations, only: [:index, :show, :new, :create]

  resources :clients do
    member do 
      get :index_invoices
    end    
    # member { put :toggle_menu_preference }
    resources :websites do 
      resources :subscriptions
      resources :features
    end
  end

  # https://mattbrictson.com/dynamic-rails-error-pages
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  

  # Consume Stripe Webhooks: https://github.com/integrallis/stripe_event
  mount StripeEvent::Engine, at: '/stripe_webhooks' # provide a custom path

  root to: "pages#welcome"

end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  uuid                   :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  provider               :string(255)
#  uid                    :string(255)
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  avatar_file_name       :string(255)
#  avatar_content_type    :string(255)
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#  oauth_avatar           :string(255)
#  invitation_token       :string(255)
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_type        :string(255)
#  invited_by_id          :integer
#  invitations_count      :integer          default(0)
#  contact_name           :string(255)
#  business_name          :string(255)
#  billing_currency       :string(255)      default("AUD")
#  stripe_account_id      :string(255)
#  admin                  :boolean
#  subscribed             :boolean          default(FALSE)
#  receipt_number         :string(255)
#  slug                   :string(255)
#
# Indexes
#
#  index_clients_on_confirmation_token    (confirmation_token) UNIQUE
#  index_clients_on_email                 (email) UNIQUE
#  index_clients_on_invitation_token      (invitation_token) UNIQUE
#  index_clients_on_invitations_count     (invitations_count)
#  index_clients_on_invited_by_id         (invited_by_id)
#  index_clients_on_reset_password_token  (reset_password_token) UNIQUE
#  index_clients_on_slug                  (slug) UNIQUE
#

class Client < ApplicationRecord
  # include ActiveUUID::UUID
  # natural_key :created_at
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :omniauthable,
         :omniauth_providers => [:facebook, :google_oauth2, :linkedin]

  #paperclip
  has_attached_file :avatar, styles: { medium: "300x300#", thumb: "100x100#" }, default_url: "default_avatar.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  #relation to websites
  has_many :websites
  accepts_nested_attributes_for :websites, :reject_if => :all_blank, :allow_destroy => true
  
  # Relation to Support Conversations
  has_many :authored_support_conversations, class_name: 'SupportConversation', foreign_key: 'author_id'
  has_many :received_support_conversations, class_name: 'SupportConversation', foreign_key: 'receiver_id'   
  has_many :messages, dependent: :destroy


  # Better URL Slugs
  extend FriendlyId
  friendly_id :business_name, use: :slugged
  validates :business_name, uniqueness: true, presence: true

  # Omniauth login
  # https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview
    def self.from_omniauth(auth, current_client)

      if current_client
        client = current_client
      elsif Client.where(email: auth.info.email)
        client = Client.where(email: auth.info.email).first
      else
        client = nil
      end
      # client = current_client ? current_client : nil
      # client = current_client
      unless client
          client = Client.create(
            email:  auth.info.email ? auth.info.email : "oauth_user: #{auth.info.name}",
            password: Devise.friendly_token[0,20],
            contact_name: auth.info.name,
            oauth_avatar: auth.info.image,
            provider: auth.provider, 
            uid: auth.uid
          )
          client.skip_confirmation!
      else
          client.update_attributes(
            contact_name: auth.info.name,
            oauth_avatar: auth.info.image,
            provider: auth.provider, 
            uid: auth.uid
          )      
          client.save
      end
      client
    end         

    def self.new_with_session(params, session)
      super.tap do |client|
        if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          client.email = data["email"] if client.email.blank?
        end
      end
    end  

    # http://stackoverflow.com/questions/21370461/connect-twitter-account-to-existing-devise-account    

    def has_connection_with(provider)
      auth = self.provider
      if (auth.present? and auth == provider)
        self.uid.present?
      else
        false
      end
    end    

  protected

    # def email_required?
    #   false
    # end

end

app/controllers/clients/confirmations_controller.rb
class Clients::ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    dashboard_index_path
  end
end

app/controllers/clients/invitations_controller.rb
class Clients::InvitationsController < Devise::InvitationsController

  before_filter :update_sanitized_params, only: :update

  def after_accept_path_for(resource)
    dashboard_index_path
  end

  # PUT /resource/invitation
  def update
    respond_to do |format|
      format.js do
        invitation_token = Devise.token_generator.digest(resource_class, :invitation_token, update_resource_params[:invitation_token])
        self.resource = resource_class.where(invitation_token: invitation_token).first
        resource.skip_password = true
        resource.update_attributes update_resource_params.except(:invitation_token)
      end
      format.html do
        super
      end
    end
  end

  # https://github.com/scambra/devise_invitable/wiki/Invite-a-Resource-(or-User)-that-Has-Already-Signed-Up-without-Invitation
  def invite_resource(&block)
    @client = Client.find_by(email: invite_params[:email])
    # @user is an instance or nil
    if @client && @client.email != current_client.email
      # invite! instance method returns a Mail::Message instance
      @client.invite!(current_client)
      # return the user instance to match expected return type
      @client
    else
      # invite! class method returns invitable var, which is a User instance
      resource_class.invite!(invite_params, current_inviter, &block)
    end
  end  


  protected

  def update_sanitized_params
    devise_parameter_sanitizer.permit(:accept_invitation, keys: [:business_name, :contact_name, :password, :password_confirmation, :invitation_token, :avatar, :avatar_cache, :hosting_units, :billing_currency])
  end
end

app/controllers/clients/omniauth_callbacks_controller.rb
class Clients::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    @client = Client.from_omniauth(request.env["omniauth.auth"], current_client)
    if @client.persisted?
      sign_in_and_redirect @client, :event => :authentication #this will throw if @client is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_client_registration_url
    end
  end

  def google_oauth2
    @client = Client.from_omniauth(request.env["omniauth.auth"], current_client)

    if @client.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @client, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"].except(:extra) #Removing extra as it can overflow some session stores
      redirect_to new_client_registration_url, alert: @client.errors.full_messages.join("\n")
    end
  end

  def linkedin
    @client = Client.from_omniauth(request.env["omniauth.auth"], current_client)

    if @client.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Linkedin"
      sign_in_and_redirect @client, :event => :authentication
    else
      session["devise.linkedin_data"] = request.env["omniauth.auth"].except(:extra) #Removing extra as it can overflow some session stores
      redirect_to new_client_registration_url, alert: @client.errors.full_messages.join("\n")
    end
  end  

  def failure
    redirect_to dashboard_index_path
  end  

end

app/controllers/clients/registrations_controller.rb
class Clients::RegistrationsController < Devise::RegistrationsController

  # def update_resource(resource, params)
  #   if resource.encrypted_password.blank? || params[:password].blank?
  #     resource.email = params[:email] if params[:email]
  #     if !params[:password].blank? && params[:password] == params[:password_confirmation]
  #       logger.info "Updating password"
  #       resource.password = params[:password]
  #       resource.save
  #     end
  #     if resource.provider
  #       resource.update_without_password(params)
  #     else
  #       resource.save       
  #     end
  #   else
  #     resource.update_with_password(params)
  #   end
  # end

  # protected

  #   def after_update_path_for(resource)
  #     root_path
  #   end  
  protected

  def update_resource(resource, params)
    if resource.provider
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end  

end

app/controllers/clients/sessions_controller.rb
class Clients::SessionsController < Devise::SessionsController

  before_filter :remove_authentication_flash_message_if_root_url_requested

  # prepend_before_filter :verify_client, only: [:destroy]

  private

  def remove_authentication_flash_message_if_root_url_requested
    if session[:user_return_to] == root_path and flash[:alert] == I18n.t('devise.failure.unauthenticated')
      flash[:alert] = nil
    end
    raise
  end

  # def verify_client
  #   ## redirect to appropriate path
  #   redirect_to new_client_session_path, notice: 'You have signed out. Please sign in again.' and return unless client_signed_in?
  # end  

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:index_invoices]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_client!
  before_action :authenticate_admin, only: [:index]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    # redirect_to root_url
    @client = Client.friendly.find(params[:id])
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
    @client = Client.friendly.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    @client = Client.friendly.find(params[:id])
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def index_invoices
    if (@client.stripe_account_id? and @client.subscribed?)
      @invoices = Stripe::Invoice.list(:customer => @client.stripe_account_id, limit: 12)
      @upcoming = Stripe::Invoice.upcoming(:customer => @client.stripe_account_id)
    else
      redirect_to dashboard_index_path, :notice => "You are not subscribed to a hosting plan; please do so below"
    end
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:avatar, :business_name, :contact_name, websites_attributes: [:id, :name, :ssl, :cdn, :_destroy])
    end

    def authenticate_admin
      unless current_client.try(:admin)
        # redirect_to root_url
        redirect_to dashboard_index_path
      end
    end   

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client.haml
%tr
  -if client.business_name?
    %td.positive
      = client.business_name
  -else
    %td.negative
      None
  -if client.contact_name?
    %td
      = client.contact_name
  -else
    %td.negative
      No Contact
  -if client.email?
    %td
      = client.email
  -else
    %td.negative
      No Contact   
  -if client.confirmed_at?
    %td.positive
      %i.icon.checkmark
      Confirmed 
  -else
    %td.negative
      %i.icon.close
      Not Confirmed
  %td.positive
    = client.billing_currency                   

%tr
  %td= link_to 'Show', client
  %td= link_to 'Edit', edit_client_path(client)
  %td
    %a{id: "modal__trigger__#{client.uuid}" }
      Resend invite
    .ui.modal.basic{id: "modal__#{client.uuid}" }
      .header Resend Invite for #{client.contact_name}
      .content
        = simple_form_for client, url: invitation_path(client), html: { method: :post} do |f|
          = f.input :email, :as => :hidden
          = f.button :submit, t("devise.invitations.new.submit_button")
    :javascript
      $("#modal__trigger__#{client.uuid}").click(function(){
        $('#modal__#{client.uuid}').modal('show');
      });
  %td= link_to 'Message', new_message_path(receiver_id: client, generic_contact: true)
  %td= link_to 'Delete', client, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/clients/_feature_fields.haml
.ui.segment.nested-fields.second-level-nested-fields
  = f.input :name
  = f.input :quantity, as: :integer
  = f.input :billing_units, as: :integer
  = link_to_remove_association "remove feature", f

app/views/clients/_form.html.haml
= simple_form_for(@client) do |f|
  / = devise_error_messages!
  = f.input :email
  = f.input :contact_name
  = f.input :business_name
  - if current_client.try(:admin?)
    = f.input :billing_currency, collection: ['AUD', 'USD']
    #websites
    = f.simple_fields_for :websites do |website|
      = render 'devise/website_fields', f: website
    .ui.field
      =link_to_add_association 'Add A Website for this client', f, :websites, class: "ui positive basic button" 
  .ui.field
    = f.button :submit, "Update"

app/views/clients/_website_fields.haml
.ui.segment.nested-fields
  = f.input :name, label: "Website Name"
  = f.input :app_type, label: "Type of Application"
  = f.input :billing_units, as: :integer, label: "Base Billing Units"
  = f.input :production_url
  = f.input :staging_url
  / = website.input :description
  / = website.input :done, :as => :boolean
  .website-features
    = f.simple_fields_for :features do |feature|
      = render 'feature_fields', f: feature
    .ui.field
      =link_to_add_association 'Add A Feature for this Site', f, :features, class: "ui basic button"   
  = link_to_remove_association "remove website", f

app/views/clients/edit.html.haml
- content_for :title, @client.business_name ? "Editing: #{@client.business_name}" : "Editing: #{@client.contact_name}"
- content_for :sub_title do 
  = "Edit your account details below"

.ui.segment.center.aligned
  = render 'form'

= link_to 'Show', @client
\|
= link_to 'Back', clients_path

app/views/clients/index.html.haml
- content_for :title, 'Clients'
- content_for :sub_title do
  = "Viewing all clients"

%table.ui.celled.table
  %thead
    %tr
      %th Business
      %th Contact
      %th Email
      %th Confirmation
      %th Currency
  %tbody
    = render @clients

/ # - @clients.each do |client|         
/ #   = react_component('PageTitle', {clientName: client.business_name ? client.business_name : client.contact_name, client: client})

/ = react_component('HelloModal')

/ = link_to 'New Client', new_client_path  .ui.divided.items
.ui.segment
  = link_to 'Invite new client', new_client_invitation_path, class: 'ui basic button fluid'

app/views/clients/index_invoices.haml
- content_for :title do
  = "Invoice History"
- content_for :sub_title do 
  = "History of your past year of invoices"

%ul.latest-charges

  %h5.pad-left Upcoming Invoice
  - invoice = @upcoming
  = render :partial => "layouts/invoice_full", locals: { invoice: @upcoming, icon: "calendar outline", inactive: false }

  %h5.pad-left Latest
  - invoice = @invoices.data.shift
  = render :partial => "layouts/invoice_full", locals: { invoice: invoice, icon: "checkmark green", inactive: false }

  %h5.pad-left{class: @invoices.data.empty? ? "faded" : "" } Completed        
  - @invoices.data.each do |invoice|  
    = render :partial => "layouts/invoice_full", locals: { invoice: invoice, icon: "checkmark", inactive: true }      

app/views/clients/new.html.haml
%h1 New client

= render 'form'

= link_to 'Back', clients_path

app/views/clients/show.html.haml
- content_for :title, @client.business_name ? @client.business_name : @client.contact_name
- content_for :sub_title do 
  = "Viewing your account details"
.ui.segment
  .ui.grid
    .ui.one.column.row
      .column
        .profile
          .ui.page.grid.one.column
            .column
              / {{&gt; userProfile}}
        .profile.ui.segments
          .ui.secondary.segment
            %h3 
              =@client.business_name
          .ui.segment    
            .meta
              %span.date Member since #{@client.created_at.year}

          .ui.segment
            %address
              %strong 
                =@client.contact_name
              %br/
              %span 
                =@client.email
          .ui.segment
            %strong
              Sites
            %br/
            -@client.websites.each do |site|
              = site.name
              = link_to "View", Domainatrix.parse(site.production_url).url, target: '_blank', style: "font-size: .8em"
              %br/
          .ui.segment
            .left.floated
              = link_to 'Edit', edit_client_path(@client)
              \|
              = link_to 'Back', clients_path   
            .right.floated{style: "font-size: .8em"}
              = link_to "Request to Cancel Subscription", new_message_path(receiver_id: @support_receiver, generic_contact: true, cancel: true)  

    .ui.three.column.stackable.row
      .column
        - fb = check_connection('facebook', 'Facebook')
        = fb.html_safe
      .column
        - google = check_connection('google_oauth2', 'Google')            
        = google.html_safe  
      .column
        - google = check_connection('linkedin', 'Linkedin')            
        = google.html_safe            